Controllers/CaixaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Gran_Prix.Data;
using Gran_Prix.Models;

namespace Gran_Prix.Controllers
{
    public class CaixaController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CaixaController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Caixa
        public async Task<IActionResult> Index()
        {
              return _context.caixa != null ? 
                          View(await _context.caixa.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.caixa'  is null.");
        }

        // GET: Caixa/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.caixa == null)
            {
                return NotFound();
            }

            var caixaModel = await _context.caixa
                .FirstOrDefaultAsync(m => m.Id == id);
            if (caixaModel == null)
            {
                return NotFound();
            }

            return View(caixaModel);
        }

        // GET: Caixa/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Caixa/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Entrada,Saida,Data,Pedido_Id")] CaixaModel caixaModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(caixaModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(caixaModel);
        }

        // GET: Caixa/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.caixa == null)
            {
                return NotFound();
            }

            var caixaModel = await _context.caixa.FindAsync(id);
            if (caixaModel == null)
            {
                return NotFound();
            }
            return View(caixaModel);
        }

        // POST: Caixa/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Entrada,Saida,Data,Pedido_Id")] CaixaModel caixaModel)
        {
            if (id != caixaModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(caixaModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CaixaModelExists(caixaModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(caixaModel);
        }

        // GET: Caixa/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.caixa == null)
            {
                return NotFound();
            }

            var caixaModel = await _context.caixa
                .FirstOrDefaultAsync(m => m.Id == id);
            if (caixaModel == null)
            {
                return NotFound();
            }

            return View(caixaModel);
        }

        // POST: Caixa/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.caixa == null)
            {
                return Problem("Entity set 'ApplicationDbContext.caixa'  is null.");
            }
            var caixaModel = await _context.caixa.FindAsync(id);
            if (caixaModel != null)
            {
                _context.caixa.Remove(caixaModel);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CaixaModelExists(int id)
        {
          return (_context.caixa?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/ClientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Gran_Prix.Data;
using Gran_Prix.Models;

namespace Gran_Prix.Controllers
{
    public class ClientesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ClientesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Clientes
        public async Task<IActionResult> Index()
        {
            return _context.clientes != null ? 
                          View(await _context.clientes.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.clientes'  is null.");
        }

        // GET: Clientes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.clientes == null)
            {
                return NotFound();
            }

            var clientesModel = await _context.clientes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (clientesModel == null)
            {
                return NotFound();
            }

            return View(clientesModel);
        }

        // GET: Clientes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Clientes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Telefone,CPF,Email")] ClientesModel clientesModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(clientesModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(clientesModel);
        }

        // GET: Clientes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.clientes == null)
            {
                return NotFound();
            }

            var clientesModel = await _context.clientes.FindAsync(id);
            if (clientesModel == null)
            {
                return NotFound();
            }
            return View(clientesModel);
        }

        // POST: Clientes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Telefone,CPF,Email")] ClientesModel clientesModel)
        {
            if (id != clientesModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(clientesModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClientesModelExists(clientesModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(clientesModel);
        }

        // GET: Clientes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.clientes == null)
            {
                return NotFound();
            }

            var clientesModel = await _context.clientes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (clientesModel == null)
            {
                return NotFound();
            }

            return View(clientesModel);
        }

        // POST: Clientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.clientes == null)
            {
                return Problem("Entity set 'ApplicationDbContext.clientes'  is null.");
            }
            var clientesModel = await _context.clientes.FindAsync(id);
            if (clientesModel != null)
            {
                _context.clientes.Remove(clientesModel);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClientesModelExists(int id)
        {
          return (_context.clientes?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/EstoqueController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Gran_Prix.Data;
using Gran_Prix.Models;

namespace Gran_Prix.Controllers
{
    public class EstoqueController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EstoqueController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Estoque
        public async Task<IActionResult> Index()
        {
              return _context.estoque != null ? 
                          View(await _context.estoque.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.estoque'  is null.");
        }

        // GET: Estoque/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.estoque == null)
            {
                return NotFound();
            }

            var estoqueModel = await _context.estoque
                .FirstOrDefaultAsync(m => m.Id == id);
            if (estoqueModel == null)
            {
                return NotFound();
            }

            return View(estoqueModel);
        }

        // GET: Estoque/Create
        public IActionResult Create()
        {
            var fornecedor = _context.fornecedor.ToList();
            ViewBag.Fornecedor = fornecedor;

            return View();
        }

        // POST: Estoque/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Preco,Quantidade,Codigo,Fornecedor_Id")] EstoqueModel estoqueModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(estoqueModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(estoqueModel);
        }

        // GET: Estoque/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            var fornecedor = _context.fornecedor.ToList();
            ViewBag.Fornecedor = fornecedor;

            if (id == null || _context.estoque == null)
            {
                return NotFound();
            }

            var estoqueModel = await _context.estoque.FindAsync(id);
            if (estoqueModel == null)
            {
                return NotFound();
            }
            return View(estoqueModel);
        }

        // POST: Estoque/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Preco,Quantidade,Codigo,Fornecedor_Id")] EstoqueModel estoqueModel)
        {
            if (id != estoqueModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(estoqueModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EstoqueModelExists(estoqueModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(estoqueModel);
        }

        // GET: Estoque/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.estoque == null)
            {
                return NotFound();
            }

            var estoqueModel = await _context.estoque
                .FirstOrDefaultAsync(m => m.Id == id);
            if (estoqueModel == null)
            {
                return NotFound();
            }

            return View(estoqueModel);
        }

        // POST: Estoque/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.estoque == null)
            {
                return Problem("Entity set 'ApplicationDbContext.estoque'  is null.");
            }
            var estoqueModel = await _context.estoque.FindAsync(id);
            if (estoqueModel != null)
            {
                _context.estoque.Remove(estoqueModel);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EstoqueModelExists(int id)
        {
          return (_context.estoque?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewData["Title"] - Meu_TCC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Meu_TCC.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css">
    <link href="https://cdn.datatables.net/v/dt/dt-1.13.6/datatables.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand fs-4" id="link" asp-area="" asp-controller="Home" asp-action="Index">
                    <i class="bi bi-box"></i>
                    EZTOCK
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">

                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <!--CAIXA-->
                        <li class="nav-item">
                            <a class="nav-link active ms-4 fs-5 fst-italic" id="link" aria-current="page" asp-area="" asp-controller="Caixa" asp-action="Index">Caixa</a>
                        </li>
                        <!--CLIENTE-->
                        <li class="nav-item">
                            <a class="nav-link active ms-4 fs-5 fst-italic" id="link" aria-current="page" asp-area="" asp-controller="Clientes" asp-action="Index">Cliente</a>
                        </li>
                        <!--FUNCIONARIO-->
                        <li class="nav-item">
                            <a class="nav-link active ms-4 fs-5 fst-italic" id="link" aria-current="page" asp-area="" asp-controller="Funcionario" asp-action="Index">Funcionario</a>
                        </li>
                        <!--FORNECEDOR-->
                        <li class="nav-item">
                            <a class="nav-link active ms-4 fs-5 fst-italic" id="link" aria-current="page" asp-area="" asp-controller="Fornecedor" asp-action="Index">Fornecedor</a>
                        </li>
                        <!--ESTOQUE-->
                        <li class="nav-item">
                            <a class="nav-link active ms-4 fs-5 fst-italic" id="link" aria-current="page" asp-area="" asp-controller="Estoque" asp-action="Index">Estoque</a>
                        </li>

                    </ul>
                    <partial name="_LoginPartial" />
                </div>


            </div>


        </nav>
    </header>    @RenderBody()
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
            crossorigin="anonymous"></script>
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.datatables.net/v/dt/dt-1.13.6/datatables.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="vendor/chart.js/Chart.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="js/demo/chart-area-demo.js"></script>
    <script src="js/demo/chart-pie-demo.js"></script>
    <style>
        #link {
            position: relative;
            color: #ffc501;
            text-decoration: none;
        }

            #link:before {
                content: "";
                position: absolute;
                width: 100%;
                height: 3px;
                bottom: 0;
                left: 0;
                background-color: #fd7e14;
                visibility: hidden;
                -webkit-transform: scaleX(0);
                transform: scaleX(0);
                -webkit-transition: all 0.3s ease-in-out 0s;
                transition: all 0.3s ease-in-out 0s;
            }

            #link:hover:before {
                visibility: visible;
                -webkit-transform: scaleX(1);
                transform: scaleX(1);
            }
    </style>
</body>
</html>