Controllers/FornecedorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Gran_Prix.Data;
using Gran_Prix.Models;

namespace Gran_Prix.Controllers
{
    public class FornecedorController : Controller
    {
        private readonly ApplicationDbContext _context;

        public FornecedorController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Fornecedor
        public async Task<IActionResult> Index()
        {
              return _context.fornecedor != null ? 
                          View(await _context.fornecedor.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.fornecedor'  is null.");
        }

        // GET: Fornecedor/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.fornecedor == null)
            {
                return NotFound();
            }

            var fornecedorModel = await _context.fornecedor
                .FirstOrDefaultAsync(m => m.Id == id);
            if (fornecedorModel == null)
            {
                return NotFound();
            }

            return View(fornecedorModel);
        }

        // GET: Fornecedor/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Fornecedor/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome")] FornecedorModel fornecedorModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(fornecedorModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(fornecedorModel);
        }

        // GET: Fornecedor/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.fornecedor == null)
            {
                return NotFound();
            }

            var fornecedorModel = await _context.fornecedor.FindAsync(id);
            if (fornecedorModel == null)
            {
                return NotFound();
            }
            return View(fornecedorModel);
        }

        // POST: Fornecedor/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome")] FornecedorModel fornecedorModel)
        {
            if (id != fornecedorModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(fornecedorModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FornecedorModelExists(fornecedorModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(fornecedorModel);
        }

        // GET: Fornecedor/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.fornecedor == null)
            {
                return NotFound();
            }

            var fornecedorModel = await _context.fornecedor
                .FirstOrDefaultAsync(m => m.Id == id);
            if (fornecedorModel == null)
            {
                return NotFound();
            }

            return View(fornecedorModel);
        }

        // POST: Fornecedor/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.fornecedor == null)
            {
                return Problem("Entity set 'ApplicationDbContext.fornecedor'  is null.");
            }
            var fornecedorModel = await _context.fornecedor.FindAsync(id);
            if (fornecedorModel != null)
            {
                _context.fornecedor.Remove(fornecedorModel);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FornecedorModelExists(int id)
        {
          return (_context.fornecedor?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/Fornecedor/Create.cshtml
@model Gran_Prix.Models.FornecedorModel

@{
    ViewData["Title"] = "Create";
}

<div class="mb-5 text-center text-black">
    <h1 class="text-black">Cadastro de Fornecedor</h1>
</div>
<hr />
<div class="container-fluid">
    <div class="row align-items-center">
        <div class="col-xl-2 col-sm-2">
            <!--LADO ESQUERDO-->
        </div>
        <div class="col-xl-8 col-sm-8 bg-dark p-5" id="teste">
            <!--CENTRO-->
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="col-12 form-group text-white">
                    <label asp-for="Nome" class="control-label"></label>
                    <input asp-for="Nome" class="form-control" />
                    <span asp-validation-for="Nome" class="text-danger"></span>
                </div>
                <div class="d-flex gap-3 mt-5">
                    <input type="submit" value="Create" class="btn btn-outline-success w-50" placeholder="Adicionar" />
                    <a class="btn btn-outline-danger text-light w-50" asp-action="Index">Cancelar</a>

                </div>
            </form>
        </div>
        <div class="col-xl-2 col-sm-2">
            <!--LADO DIREITO-->
        </div>
    </div>
</div>

<style>
    #teste {
        opacity: 0.8;
        border-radius: 15px;
    }
</style>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Fornecedor/Delete.cshtml
@model Gran_Prix.Models.FornecedorModel

@{
    ViewData["Title"] = "Delete";
}

<div class="mb-5 text-center text-black">
    <h1 class="text-black">Excluir Funcionario</h1>
</div>
<hr />

<div style="margin-left:35%">
    <dl class="row">
        <dt class = "col-sm-2 fs-5">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10 fs-5">
            @Html.DisplayFor(model => model.Nome)
        </dd>
    </dl>
</div>

<hr />

<div style="margin-left:35%">
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <div class="d-flex gap-3 mt-5">
            <input type="submit" value="Delete" class="btn btn-danger" style="width:20%" />
            <a class="btn btn-outline-secondary" style="width:20%" asp-action="Index">Back</a>
        </div>
    </form>
</div>

Views/Fornecedor/Details.cshtml
@model Gran_Prix.Models.FornecedorModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>FornecedorModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Fornecedor/Edit.cshtml
@model Gran_Prix.Models.FornecedorModel

@{
    ViewData["Title"] = "Edit";
}

<div class="mb-5 text-center text-black">
    <h1 class="text-black">Editar Fornecedores</h1>
</div>
<hr />
<div class="container-fluid">
    <div class="row align-items-center">
        <div class="col-xl-2 col-sm-2">
            <!--LADO ESQUERDO-->
        </div>
        <div class="col-xl-8 col-sm-8 bg-dark p-5" id="teste">
            <!--CENTRO-->
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="col-12 form-group text-white">
                    <label asp-for="Nome" class="control-label"></label>
                    <input asp-for="Nome" class="form-control" />
                    <span asp-validation-for="Nome" class="text-danger"></span>
                </div>
                <div class="d-flex gap-3 mt-5">
                    <input type="submit" value="Save" class="btn btn-outline-success w-50" placeholder="Adicionar" />
                    <a class="btn btn-outline-danger w-50" asp-action="Index">Back</a>

                </div>
            </form>
        </div>
        <div class="col-xl-2 col-sm-2">
            <!--LADO DIREITO-->
        </div>
    </div>
</div>

<style>
    #teste {
        opacity: 0.8;
        border-radius: 15px;
    }
</style>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Fornecedor/Index.cshtml
@model IEnumerable<Gran_Prix.Models.FornecedorModel>

@{
    ViewData["Title"] = "Index";
}

<div class="d-flex justify-content-between align-items-center mb-5 mt-2 border-bottom">
    <h1 class="container">Fornecedores</h1>

    <a class="btn mx-5" asp-controller="Fornecedor" asp-action="Create"><i class="bi bi-truck fs-3">+</i></a>

</div>

<div class="container">

    <table id="Fornecedores" class="table table-dark table-striped mt-5">

        <br />
        <thead>
            <tr>
                <th scope="col">Código</th>
                <th scope="col">Nome</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null)
            {

                @foreach (var fornecedores in Model)

                {
                    <tr>
                        <td scope="row">@fornecedores.Id</td>
                        <td scope="row">@fornecedores.Nome</td>
                        <td>
                            <!--EXCLUIR-->
                            <a class="btn text-white mx-2 float-end" asp-controller="Fornecedor" asp-action="Excluir"
                               asp-route-id="@fornecedores.Id"><i class="bi bi-trash-fill"></i></a>
                            <!--EDITAR-->
                            <a class="btn text-white mx-2 float-end" asp-controller="Fornecedor" asp-action="Editar"
                               asp-route-id="@fornecedores.Id"><i class="bi bi-pencil"></i></a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>