Controllers/FuncionarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Gran_Prix.Data;
using Gran_Prix.Models;

namespace Gran_Prix.Controllers
{
    public class FuncionarioController : Controller
    {
        private readonly ApplicationDbContext _context;

        public FuncionarioController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Funcionario
        public async Task<IActionResult> Index()
        {
              return _context.funcionario != null ? 
                          View(await _context.funcionario.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.funcionario'  is null.");
        }

        // GET: Funcionario/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.funcionario == null)
            {
                return NotFound();
            }

            var funcionarioModel = await _context.funcionario
                .FirstOrDefaultAsync(m => m.Id == id);
            if (funcionarioModel == null)
            {
                return NotFound();
            }

            return View(funcionarioModel);
        }

        // GET: Funcionario/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Funcionario/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Telefone,CPF,Codigo")] FuncionarioModel funcionarioModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(funcionarioModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(funcionarioModel);
        }

        // GET: Funcionario/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.funcionario == null)
            {
                return NotFound();
            }

            var funcionarioModel = await _context.funcionario.FindAsync(id);
            if (funcionarioModel == null)
            {
                return NotFound();
            }
            return View(funcionarioModel);
        }

        // POST: Funcionario/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Telefone,CPF,Codigo")] FuncionarioModel funcionarioModel)
        {
            if (id != funcionarioModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(funcionarioModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FuncionarioModelExists(funcionarioModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(funcionarioModel);
        }

        // GET: Funcionario/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.funcionario == null)
            {
                return NotFound();
            }

            var funcionarioModel = await _context.funcionario
                .FirstOrDefaultAsync(m => m.Id == id);
            if (funcionarioModel == null)
            {
                return NotFound();
            }

            return View(funcionarioModel);
        }

        // POST: Funcionario/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.funcionario == null)
            {
                return Problem("Entity set 'ApplicationDbContext.funcionario'  is null.");
            }
            var funcionarioModel = await _context.funcionario.FindAsync(id);
            if (funcionarioModel != null)
            {
                _context.funcionario.Remove(funcionarioModel);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FuncionarioModelExists(int id)
        {
          return (_context.funcionario?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/Funcionario/Create.cshtml
@model Gran_Prix.Models.FuncionarioModel

@{
    ViewData["Title"] = "Create";
}

<div class="mb-5 text-center text-black">
    <h1 class="text-black">Cadastro de Funcionário</h1>
</div>
<hr />
<div class="container-fluid">
    <div class="row align-items-center">
        <div class="col-xl-2 col-sm-2">
            <!--LADO ESQUERDO-->
        </div>
        <div class="col-xl-8 col-sm-8 bg-dark p-5" id="teste">
            <!--CENTRO-->
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="col-12 form-group text-white">
                    <label asp-for="Nome" class="control-label"></label>
                    <input asp-for="Nome" class="form-control" />
                    <span asp-validation-for="Nome" class="text-danger"></span>
                </div>
                <div class="row">

                    <div class="col-5 form-group text-white">
                        <label asp-for="CPF" class="control-label"></label>
                        <input asp-for="CPF" class="form-control" />
                        <span asp-validation-for="CPF" class="text-danger"></span>
                    </div>
                    <div class="col-5 form-group text-white">
                        <label asp-for="Telefone" class="control-label"></label>
                        <input asp-for="Telefone" class="form-control" />
                        <span asp-validation-for="Telefone" class="text-danger"></span>
                    </div>
                    <div class="col-2 form-group text-white">
                        <label asp-for="Codigo" class="control-label"></label>
                        <input asp-for="Codigo" class="form-control" />
                        <span asp-validation-for="Codigo" class="text-danger"></span>
                    </div>
                </div>
                <div class="d-flex gap-3 mt-5">
                    <input type="submit" value="Create" class="btn btn-outline-success w-50" placeholder="Adicionar" />
                    <a class="btn btn-outline-danger w-50" asp-action="Index">Back</a>

                </div>
            </form>
        </div>
        <div class="col-xl-2 col-sm-2">
            <!--LADO DIREITO-->
        </div>
    </div>
</div>

<style>
    #teste {
        opacity: 0.8;
        border-radius: 15px;
    }
</style>

<!--CÒDIGO ORGINAL-->
@*<h1>Create</h1>

<h4>FuncionarioModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefone" class="control-label"></label>
                <input asp-for="Telefone" class="form-control" />
                <span asp-validation-for="Telefone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CPF" class="control-label"></label>
                <input asp-for="CPF" class="form-control" />
                <span asp-validation-for="CPF" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>*@

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Funcionario/Delete.cshtml
@model Gran_Prix.Models.FuncionarioModel

@{
    ViewData["Title"] = "Delete";
}

<div class="mb-5 text-center text-black">
    <h1 class="text-black">Excluir Funcionario</h1>
</div>
<hr />

<div style="margin-left:35%">
    <dl class="row">
        <dt class="col-sm-2 fs-5">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class="col-sm-10 fs-5">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class="col-sm-2 fs-5">
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>
        <dd class="col-sm-10 fs-5">
            @Html.DisplayFor(model => model.Telefone)
        </dd>
        <dt class="col-sm-2 fs-5">
            @Html.DisplayNameFor(model => model.CPF)
        </dt>
        <dd class="col-sm-10 fs-5">
            @Html.DisplayFor(model => model.CPF)
        </dd>
        <dt class="col-sm-2 fs-5">
            @Html.DisplayNameFor(model => model.Codigo)
        </dt>
        <dd class="col-sm-10 fs-5">
            @Html.DisplayFor(model => model.Codigo)
        </dd>
    </dl>
</div>

<hr />

<div style="margin-left:35%">
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <div class="d-flex gap-3 mt-5">
            <input type="submit" value="Delete" class="btn btn-danger" style="width:20%" />
            <a class="btn btn-outline-secondary" style="width:20%" asp-action="Index">Back</a>
        </div>
    </form>
</div>

Views/Funcionario/Details.cshtml
@model Gran_Prix.Models.FuncionarioModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>FuncionarioModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CPF)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CPF)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Codigo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Codigo)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Funcionario/Edit.cshtml
@model Gran_Prix.Models.FuncionarioModel

@{
    ViewData["Title"] = "Edit";
}

<div class="mb-5 text-center text-black">
    <h1 class="text-black">Editar Funcionário</h1>
</div>
<hr />
<div class="container-fluid">
    <div class="row align-items-center">
        <div class="col-xl-2 col-sm-2">
            <!--LADO ESQUERDO-->
        </div>
        <div class="col-xl-8 col-sm-8 bg-dark p-5" id="teste">
            <!--CENTRO-->
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="col-12 form-group text-white">
                    <label asp-for="Nome" class="control-label"></label>
                    <input asp-for="Nome" class="form-control" />
                    <span asp-validation-for="Nome" class="text-danger"></span>
                </div>
                <div class="row">

                    <div class="col-5 form-group text-white">
                        <label asp-for="CPF" class="control-label"></label>
                        <input asp-for="CPF" class="form-control" />
                        <span asp-validation-for="CPF" class="text-danger"></span>
                    </div>
                    <div class="col-5 form-group text-white">
                        <label asp-for="Telefone" class="control-label"></label>
                        <input asp-for="Telefone" class="form-control" />
                        <span asp-validation-for="Telefone" class="text-danger"></span>
                    </div>
                    <div class="col-2 form-group text-white">
                        <label asp-for="Codigo" class="control-label"></label>
                        <input asp-for="Codigo" class="form-control" />
                        <span asp-validation-for="Codigo" class="text-danger"></span>
                    </div>
                </div>
                <div class="d-flex gap-3 mt-5">
                    <input type="submit" value="Save" class="btn btn-outline-success w-50" placeholder="Adicionar" />
                    <a class="btn btn-outline-danger w-50" asp-action="Index">Back</a>

                </div>
            </form>
        </div>
        <div class="col-xl-2 col-sm-2">
            <!--LADO DIREITO-->
        </div>
    </div>
</div>

<style>
    #teste {
        opacity: 0.8;
        border-radius: 15px;
    }
</style>

@*<h1>Edit</h1>

<h4>FuncionarioModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefone" class="control-label"></label>
                <input asp-for="Telefone" class="form-control" />
                <span asp-validation-for="Telefone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CPF" class="control-label"></label>
                <input asp-for="CPF" class="form-control" />
                <span asp-validation-for="CPF" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Codigo" class="control-label"></label>
                <input asp-for="Codigo" class="form-control" />
                <span asp-validation-for="Codigo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
*@
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Funcionario/Index.cshtml
@model IEnumerable<Gran_Prix.Models.FuncionarioModel>

@{
    ViewData["Title"] = "Index";
}

<div class="d-flex justify-content-between align-items-center mb-5 mt-2 border-bottom">
    <h1 class="container">Funcionarios</h1>

    <a class="btn mx-5" asp-controller="Funcionario" asp-action="Create"><i class="bi bi-person-plus fs-3"></i></a>

</div>

<div class="container">

    <table id="Funcionario" class="table table-dark table-striped mt-5">
        <thead>
            <tr>
                <th scope="col">Nome</th>
                <th scope="col">Telefone</th>
                <th scope="col">CPF</th>
                <th scope="col">Código</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null)
            {

                @foreach (var funcioanrio in Model)

                {
                    <tr>
                        <td scope="row">@funcioanrio.Nome</td>
                        <td scope="row">@funcioanrio.Telefone</td>
                        <td scope="row">@funcioanrio.CPF</td>
                        <td scope="row">@funcioanrio.Codigo</td>
                        <td>
                            
                            <!--EXCLUIR-->
                            <a class="btn text-white mx-2 float-end" asp-action="Delete"
                               asp-route-id="@funcioanrio.Id"><i class="bi bi-trash-fill"></i></a>
                            <!--EDITAR-->
                            <a class="btn text-white mx-2 float-end" asp-action="Edit"
                               asp-route-id="@funcioanrio.Id"><i class="bi bi-pencil"></i></a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

@*<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telefone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CPF)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Codigo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CPF)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Codigo)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
*@